server:
  port: 7002

eureka:
  instance:
    hostname: eureka02.com        #eureka服务端的实例名称
  client:
    register-with-eureka: false   #false表示不向注册中心注册自己
    fetch-registry: false         #false表示自己端就是注册中心，我的职责就是维护服务实例，并不需要去检索服务
    service-url:
#      设置与Eureka Server交互的地址查询服务和注册服务都需要依赖这个地址（单机）
#      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/   #（单机）
      defaultZone: http://mace:liuye0425@eureka01.com:7001/eureka/                            #（集群，多个用逗号隔开）

spring:
  aop:
    proxy-target-class: true      #使用 CGLIB 来实现AOP false:使用的是标准Java的实现。

security:
  user:
    name: mace
    password: liuye0425